"""New Migration

Revision ID: 8d911b450241
Revises: 
Create Date: 2023-11-14 22:52:44.910550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d911b450241'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activities', 'uid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meals', 'm_type',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    op.alter_column('workouts', 'w_type',
               existing_type=sa.CHAR(length=1),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workouts', 'w_type',
               existing_type=sa.String(),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.alter_column('meals', 'm_type',
               existing_type=sa.String(),
               type_=sa.CHAR(length=1),
               existing_nullable=True)
    op.alter_column('activities', 'uid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
